permalink: :slug
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: post
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
